import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { INCOME_RULES, EXPENSE_RULES, normalize, canonicalCategoryName, inferTransactionType } from "https://raw.githubusercontent.com/jsuryanaads/WeMONEY/main/src/services/hybridAiRules.js";
import { parseNaturalTransaction, normalizeNaturalLanguage, transactionDateLabel } from "./nlu.ts";
import { classifyWithOpenRouter, routeWithOpenRouter } from "./ai.ts";
import { routeTelegramIntent, monthBounds, monthLabel, formatRupiah, summarizeTransactions, renderIntentHelp } from "./intentRouter.ts";

const URL = Deno.env.get("SUPABASE_URL")!;
const KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(URL, KEY);
const C = { "Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods":"GET,POST,OPTIONS" };
const out = (x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json",...C}});
const rupiah=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const AI_THRESHOLD=0.70;

async function token(){const{data,error}=await db.rpc("get_telegram_bot_token");if(error||!data)throw Error("TELEGRAM_BOT_TOKEN belum dikonfigurasi");return String(data)}
async function tg(method:string,body:Record<string,unknown>={}){const r=await fetch(`https://api.telegram.org/bot${await token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!d.ok)throw Error(d.description||"Telegram API error");return d}
function parse(text:string){return parseNaturalTransaction(text)}
function categoryCandidates(text:string,type:string,cats:any[]){const pool=(cats||[]).filter(c=>c.is_active!==false&&c.type===type);const lower=normalizeNaturalLanguage(text);return pool.map((c:any)=>{const name=canonicalCategoryName(c.name);let score=0,reason="";if(name&&lower.includes(name)){score=100;reason="nama kategori disebut"}const rules=type==="income"?INCOME_RULES:EXPENSE_RULES;for(const[r,patterns]of rules)if(canonicalCategoryName(r)===name&&patterns.some(x=>lower.includes(normalize(x)))){score=Math.max(score,90);reason=`kata kunci cocok dengan ${c.name}`}for(const t of name.split(/[^a-z0-9]+/).filter(x=>x.length>=3))if(lower.includes(t))score+=15;return{c,score,reason}}).sort((a,b)=>b.score-a.score)}

async function classify(uid:string,p:{type:"income"|"expense",amount:number,description:string}){
 const[{data:cats},{data:wallets}]=await Promise.all([db.from("categories").select("id,name,type,is_active").eq("user_id",uid).eq("is_active",true).eq("type",p.type),db.from("wallets").select("id,name,is_active").eq("user_id",uid).eq("is_active",true).order("created_at",{ascending:true})]);
 const ranked=categoryCandidates(p.description,p.type,cats||[]),best=ranked[0],strong=!!best&&best.score>=80,cat=strong?best.c:null,candidates=ranked.filter(x=>canonicalCategoryName(x.c.name)!=="lainnya").slice(0,3).map(x=>({id:x.c.id,name:x.c.name,score:x.score}));
 const wallet=(wallets||[]).find((w:any)=>normalize(p.description).includes(normalize(w.name)))||(wallets||[]).find((w:any)=>canonicalCategoryName(w.name)==="kas utama")||(wallets||[])[0];
 let result={categoryId:cat?.id||null,categoryName:cat?.name||null,categoryCandidates:candidates,walletId:wallet?.id||null,walletName:wallet?.name||null,confidence:strong&&wallet?.id?0.93:strong||wallet?.id?0.65:0.35,source:"local",model:null as string|null};
 if(result.confidence<AI_THRESHOLD){
   try{
    const ai=await classifyWithOpenRouter({text:p.description,amount:p.amount,transaction_date:p.transaction_date,categories:(cats||[]).map((c:any)=>({name:c.name,type:c.type})),wallets:(wallets||[]).map((w:any)=>({name:w.name}))});
    const r=ai?.result;
    const aiType=r?.type==="income"||r?.type==="expense"?r.type:null;
    const aiAmount=Number(r?.amount);
    const aiDate=typeof r?.transaction_date==="string"?r.transaction_date:null;
    const aiCat=(cats||[]).find((c:any)=>normalize(c.name)===normalize(String(r?.category_name||"")));
    const aiWallet=(wallets||[]).find((w:any)=>normalize(w.name)===normalize(String(r?.wallet_name||"")));
    const aiConfidence=Math.min(Math.max(Number(r?.confidence)||0,0),0.89);
    const valid=aiType===p.type&&aiAmount===p.amount&&!!aiDate&&/^(\d{4})-(\d{2})-(\d{2})$/.test(aiDate)&&!!aiCat&&!!aiWallet&&aiConfidence>=AI_THRESHOLD;
    if(valid){result={categoryId:aiCat.id,categoryName:aiCat.name,categoryCandidates:candidates,walletId:aiWallet.id,walletName:aiWallet.name,confidence:aiConfidence,source:"openrouter",model:ai?.model||null};}
   }catch(e){console.error("telegram openrouter fallback",e)}
 }
 return result;
}

function command(msg:any){const raw=String(msg?.text??msg?.caption??"").replace(/[\u200B-\u200D\uFEFF]/g,"").trim();if(!raw.startsWith("/"))return{raw,cmd:"",arg:""};const first=raw.split(/\s+/)[0],m=first.match(/^\/([A-Za-z0-9_]+)(?:@([A-Za-z0-9_]+))?$/);return{raw,cmd:m?.[1]?.toLowerCase()||"",arg:raw.slice(first.length).trim()}}
async function dedupe(id:number){const{error}=await db.from("telegram_webhook_updates").insert({update_id:id});if(!error)return true;if(error.code==="23505")return false;console.error(error);return true}
function categoryKeyboard(candidates:any[]){return candidates.slice(0,3).map(c=>[{text:`📂 ${String(c.name).slice(0,30)}`,callback_data:`cat:${c.id}`}])}
async function sendConfirmation(chat:string,p:any){const rows=[];if(p.categoryCandidates?.length&&!p.category_id)rows.push(...categoryKeyboard(p.categoryCandidates));rows.push([{text:p.category_id?"✅ Simpan":"⚠️ Pilih Kategori",callback_data:p.category_id?"confirm":"noop"},{text:"❌ Batal",callback_data:"cancel"}]);await tg("sendMessage",{chat_id:chat,text:`🧾 *Konfirmasi Transaksi*\n\n${p.transaction_type==="expense"?"Pengeluaran":"Pemasukan"}: ${rupiah(Number(p.amount))}\nKeterangan: ${p.description}\nKategori: ${p.category_name||"⚠️ Belum yakin — pilih salah satu"}\nDompet: ${p.wallet_name||"⚠️ Belum ada"}\nTanggal: ${p.transaction_date?transactionDateLabel(p.transaction_date):"Hari ini"}\nAI confidence: ${Math.round(Number(p.ai_confidence||0)*100)}%${p.ai_source?`\nAI source: ${p.ai_source}${p.ai_model?` (${p.ai_model})`:""}`:""}\n\n${p.category_id?"Pilih tindakan:":"AI menemukan beberapa kandidat kategori. Pilih yang paling sesuai:"}`,parse_mode:"Markdown",reply_markup:{inline_keyboard:rows}})}

async function process(u:any){try{if(u.callback_query){const cb=u.callback_query,chat=String(cb.message?.chat?.id||""),data=String(cb.data||"");await tg("answerCallbackQuery",{callback_query_id:cb.id});const{data:cn}=await db.from("telegram_connections").select("user_id").eq("telegram_chat_id",chat).eq("status","active").maybeSingle();if(!cn)return;const{data:p}=await db.from("telegram_pending_transactions").select("*").eq("user_id",cn.user_id).eq("telegram_chat_id",chat).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!p){await tg("sendMessage",{chat_id:chat,text:"⚠️ Transaksi sudah kedaluwarsa. Silakan kirim ulang."});return}if(data==="cancel"){await db.from("telegram_pending_transactions").delete().eq("id",p.id);await tg("sendMessage",{chat_id:chat,text:"❌ Transaksi dibatalkan."});return}if(data==="noop"){await tg("sendMessage",{chat_id:chat,text:"⚠️ Pilih salah satu kategori terlebih dahulu."});return}if(data.startsWith("cat:")){const id=data.slice(4),{data:cat}=await db.from("categories").select("id,name,type,is_active").eq("id",id).eq("user_id",cn.user_id).eq("is_active",true).eq("type",p.transaction_type).maybeSingle();if(!cat){await tg("sendMessage",{chat_id:chat,text:"⚠️ Kategori tidak valid atau sudah tidak aktif."});return}await db.from("telegram_pending_transactions").update({category_id:cat.id,category_name:cat.name}).eq("id",p.id);await tg("sendMessage",{chat_id:chat,text:`📂 Kategori dipilih: *${cat.name}*`,parse_mode:"Markdown"});await sendConfirmation(chat,{...p,category_id:cat.id,category_name:cat.name});return}if(data==="confirm"){if(!p.category_id){await tg("sendMessage",{chat_id:chat,text:"⚠️ Pilih kategori terlebih dahulu sebelum menyimpan."});return}const{error}=await db.rpc("telegram_create_transaction",{p_chat_id:chat,p_type:p.transaction_type,p_amount:p.amount,p_description:p.description,p_date:p.transaction_date,p_wallet_id:p.wallet_id||null,p_category_id:p.category_id||null});if(error){await tg("sendMessage",{chat_id:chat,text:`❌ Gagal menyimpan transaksi: ${error.message}`});return}await db.from("telegram_pending_transactions").delete().eq("id",p.id);await tg("sendMessage",{chat_id:chat,text:`✅ *Tersimpan*\n${p.transaction_type==="expense"?"Pengeluaran":"Pemasukan"}: ${rupiah(Number(p.amount))}\nKeterangan: ${p.description}\nKategori: ${p.category_name}\nDompet: ${p.wallet_name||"Default"}\nTanggal: ${p.transaction_date}`,parse_mode:"Markdown"});return}return}
 const msg=u.message;if(!msg?.chat?.id)return;const chat=String(msg.chat.id),{raw,cmd,arg}=command(msg);if(cmd==="start"){await tg("sendMessage",{chat_id:chat,text:"🤖 *We MONEY Bot*\n\n/start — bantuan\n/hubungkan KODE — hubungkan akun\n/status — cek koneksi\n/batal — batalkan\n\nContoh:\n• `beli makan 25rb`\n• `uang masuk dari usaha 500rb`\n• `pemasukan gaji 5jt`\n\nBot meminta konfirmasi sebelum menyimpan.",parse_mode:"Markdown"});return}if(cmd==="hubungkan"){if(!arg){await tg("sendMessage",{chat_id:chat,text:"Gunakan: /hubungkan KODE\nKode dibuat di We MONEY → Pengaturan → Telegram."});return}const{error}=await db.rpc("telegram_link_account",{p_code:arg,p_chat_id:chat,p_username:msg.from?.username||null,p_first_name:msg.from?.first_name||null});await tg("sendMessage",{chat_id:chat,text:error?`❌ ${error.message}`:"✅ Telegram berhasil terhubung. Sekarang kirim transaksi seperti `beli makan 25rb`.",parse_mode:"Markdown"});return}if(cmd==="status"){const{data}=await db.from("telegram_connections").select("telegram_username").eq("telegram_chat_id",chat).eq("status","active").maybeSingle();await tg("sendMessage",{chat_id:chat,text:data?`🟢 Terhubung${data.telegram_username?` sebagai @${data.telegram_username}`:""}.`:"🔴 Belum terhubung."});return}if(cmd==="batal"){await db.from("telegram_pending_transactions").delete().eq("telegram_chat_id",chat);await tg("sendMessage",{chat_id:chat,text:"❌ Transaksi tertunda dibatalkan."});return}const{data:cn}=await db.from("telegram_connections").select("user_id").eq("telegram_chat_id",chat).eq("status","active").maybeSingle();if(!cn){await tg("sendMessage",{chat_id:chat,text:"🔒 Telegram belum terhubung. Buka We MONEY → Pengaturan → Telegram."});return}let intent=routeTelegramIntent(raw);let period="unknown";if(intent==="unknown"){const{data:state}=await db.from("telegram_conversation_state").select("state").eq("user_id",cn.user_id).eq("telegram_chat_id",chat).maybeSingle();const aiIntent=await routeWithOpenRouter({text:raw,previousIntent:state?.state?.intent});if(aiIntent&&aiIntent.confidence>=0.70){intent=aiIntent.intent;period=aiIntent.period}}if(intent!=="transaction"&&intent!=="unknown"){await db.from("telegram_conversation_state").upsert({user_id:cn.user_id,telegram_chat_id:chat,state:{intent,period,last_text:raw},updated_at:new Date().toISOString()},{onConflict:"user_id,telegram_chat_id"});}
if(intent!=="transaction"&&intent!=="unknown"){
  if(intent==="help"){await tg("sendMessage",{chat_id:chat,text:renderIntentHelp(),parse_mode:"Markdown"});return}
  if(intent==="ai_info"){await tg("sendMessage",{chat_id:chat,text:"🤖 *AI WeMONEY Assistant*\\n\\nSaya menggunakan pendekatan *Hybrid AI*:\\n• *Local AI/Rules* — memahami pola transaksi umum secara cepat.\\n• *OpenRouter* — digunakan sebagai AI fallback ketika pemahaman lokal belum cukup yakin.\\n• Data saldo, transaksi, dompet, dan anggaran tetap diambil dari database WeMONEY; AI tidak mengarang data keuangan.\\n\\nModel OpenRouter mengikuti konfigurasi model pada server WeMONEY." ,parse_mode:"Markdown"});return}
  if(intent==="wallets"){
    const{data:ws,error}=await db.from("wallets").select("name,initial_balance,is_active").eq("user_id",cn.user_id).eq("is_active",true).order("created_at",{ascending:true});
    if(error){await tg("sendMessage",{chat_id:chat,text:"❌ Gagal membaca dompet."});return}
    const{data:ts}=await db.from("transactions").select("wallet_id,type,amount").eq("user_id",cn.user_id);
    const{data:xs}=await db.from("transfers").select("source_wallet_id,destination_wallet_id,amount").eq("user_id",cn.user_id);
    const rows=(ws||[]).map((w:any)=>({name:w.name,balance:Number(w.initial_balance)||0,id:w.id}));
    for(const t of ts||[]){const row=rows.find(x=>x.id===t.wallet_id);if(row)row.balance+=t.type==="income"?Number(t.amount): -Number(t.amount)}
    for(const x of xs||[]){const a=rows.find(r=>r.id===x.source_wallet_id);const b=rows.find(r=>r.id===x.destination_wallet_id);if(a)a.balance-=Number(x.amount);if(b)b.balance+=Number(x.amount)}
    await tg("sendMessage",{chat_id:chat,text:rows.length?"👛 *Dompet aktif*\\n\\n"+rows.map(r=>`• *${r.name}*: ${formatRupiah(r.balance)}`).join("\\n"):"Belum ada dompet aktif.",parse_mode:"Markdown"});return
  }
  const {startDate,endDate}=monthBounds();
  const{data:rows,error}=await db.from("transactions").select("type,amount,category:categories(name)").eq("user_id",cn.user_id).gte("transaction_date",startDate).lte("transaction_date",endDate);
  if(error){await tg("sendMessage",{chat_id:chat,text:"❌ Gagal membaca transaksi."});return}
  if(intent==="expense_summary"||intent==="income_summary"){
    const s=summarizeTransactions(rows||[]);
    const value=intent==="expense_summary"?s.expense:s.income;
    const label=intent==="expense_summary"?"Pengeluaran":"Pemasukan";
    const top=intent==="expense_summary"?Array.from(s.byCategory.entries()).sort((a,b)=>b[1]-a[1]).slice(0,5):[];
    let text=`📊 *${label} ${monthLabel()}*\\n\\n💰 ${formatRupiah(value)}`;
    if(intent==="expense_summary"&&top.length)text+="\\n\\nKategori terbesar:\\n"+top.map(([name,v])=>`• ${name}: ${formatRupiah(v)}`).join("\\n");
    await tg("sendMessage",{chat_id:chat,text,parse_mode:"Markdown"});return
  }
  if(intent==="balance"){
    const{data:ws,error:we}=await db.from("wallets").select("id,name,initial_balance").eq("user_id",cn.user_id).eq("is_active",true).order("created_at",{ascending:true});
    const{data:ts,error:te}=await db.from("transactions").select("wallet_id,type,amount").eq("user_id",cn.user_id);
    const{data:xs,error:xe}=await db.from("transfers").select("source_wallet_id,destination_wallet_id,amount").eq("user_id",cn.user_id);
    if(we||te||xe){await tg("sendMessage",{chat_id:chat,text:"❌ Gagal membaca saldo."});return}
    const balances=Object.fromEntries((ws||[]).map((w:any)=>[w.id,Number(w.initial_balance)||0]));
    for(const t of ts||[])if(balances[t.wallet_id]!==undefined)balances[t.wallet_id]+=t.type==="income"?Number(t.amount):-Number(t.amount);
    for(const x of xs||[]){if(balances[x.source_wallet_id]!==undefined)balances[x.source_wallet_id]-=Number(x.amount);if(balances[x.destination_wallet_id]!==undefined)balances[x.destination_wallet_id]+=Number(x.amount)}
    const total=(ws||[]).reduce((s:number,w:any)=>s+(balances[w.id]||0),0);
    await tg("sendMessage",{chat_id:chat,text:(ws||[]).length?`💰 *Saldo Saat Ini*\\n\\n${(ws||[]).map((w:any)=>`• *${w.name}*: ${formatRupiah(balances[w.id]||0)}`).join("\\n")}\\n\\n*Total: ${formatRupiah(total)}*`:"Belum ada dompet aktif.",parse_mode:"Markdown"});return
  }
  if(intent==="budget"){
    const{data:budgets,error:be}=await db.from("budgets").select("name,amount,period,start_date,end_date,category:categories(name)").eq("user_id",cn.user_id).eq("is_active",true).order("start_date",{ascending:false});
    if(be){await tg("sendMessage",{chat_id:chat,text:"❌ Gagal membaca anggaran."});return}
    const active=(budgets||[]).filter((b:any)=>b.start_date<=endDate&&(b.end_date?b.end_date>=startDate:true)).slice(0,8);
    if(!active.length){await tg("sendMessage",{chat_id:chat,text:`🎯 *Anggaran ${monthLabel()}*\\n\\nBelum ada anggaran aktif untuk periode ini.`,parse_mode:"Markdown"});return}
    const lines=active.map((b:any)=>{const actual=(rows||[]).filter((t:any)=>t.type==="expense"&&(!b.category?.name||t.category?.name===b.category.name)).reduce((s:number,t:any)=>s+Number(t.amount||0),0);const limit=Number(b.amount||0);const pct=limit>0?Math.round(actual/limit*100):0;return `• *${b.name}*: ${formatRupiah(actual)} / ${formatRupiah(limit)} (${pct}%)`});
    await tg("sendMessage",{chat_id:chat,text:`🎯 *Anggaran ${monthLabel()}*\\n\\n${lines.join("\\n")}`,parse_mode:"Markdown"});return
  }
}
const pendingForReply=await db.from("telegram_pending_transactions").select("*").eq("user_id",cn.user_id).eq("telegram_chat_id",chat).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle();if(pendingForReply.data && /^(iya|ya|yes|oke|ok|simpan|lanjut|benar|betul|setuju)$/i.test(raw)){const p=pendingForReply.data;if(!p.category_id){await tg("sendMessage",{chat_id:chat,text:"⚠️ Pilih kategori terlebih dahulu sebelum saya menyimpan transaksi ini."});return}const{error}=await db.rpc("telegram_create_transaction",{p_chat_id:chat,p_type:p.transaction_type,p_amount:p.amount,p_description:p.description,p_date:p.transaction_date,p_wallet_id:p.wallet_id||null,p_category_id:p.category_id||null});if(error){await tg("sendMessage",{chat_id:chat,text:"❌ Gagal menyimpan transaksi: "+error.message});return}await db.from("telegram_pending_transactions").delete().eq("id",p.id);await tg("sendMessage",{chat_id:chat,text:"✅ *Tersimpan*\n"+(p.transaction_type==="expense"?"Pengeluaran":"Pemasukan")+": "+rupiah(Number(p.amount))+"\nKeterangan: "+p.description+"\nKategori: "+p.category_name+"\nDompet: "+(p.wallet_name||"Default")+"\nTanggal: "+p.transaction_date,parse_mode:"Markdown"});return}const p=parse(raw);if(intent==="transaction"&&!p){await tg("sendMessage",{chat_id:chat,text:"Saya memahami ini sebagai transaksi, tetapi nominalnya belum jelas. Contoh: beli makan 25rb atau gaji masuk 5jt."});return}if(intent==="unknown"||!p){await tg("sendMessage",{chat_id:chat,text:"Saya belum yakin maksudnya. Coba jelaskan apa yang ingin dicatat atau ditanyakan, misalnya: berapa pengeluaran saya bulan ini?"});return}const ai=await classify(cn.user_id,p);await db.from("telegram_pending_transactions").delete().eq("telegram_chat_id",chat);const{error}=await db.from("telegram_pending_transactions").insert({user_id:cn.user_id,telegram_chat_id:chat,transaction_type:p.type,amount:p.amount,description:p.description,transaction_date:p.transaction_date,wallet_id:ai.walletId,category_id:ai.categoryId,wallet_name:ai.walletName,category_name:ai.categoryName});if(error){await tg("sendMessage",{chat_id:chat,text:`❌ Gagal membuat draft: ${error.message}`});return}await sendConfirmation(chat,{transaction_type:p.type,amount:p.amount,description:p.description,transaction_date:p.transaction_date,wallet_id:ai.walletId,category_id:ai.categoryId,wallet_name:ai.walletName,category_name:ai.categoryName,categoryCandidates:ai.categoryCandidates,ai_confidence:ai.confidence,ai_source:ai.source,ai_model:ai.model});}catch(e){console.error("telegram process",e)}}
Deno.serve(async req=>{try{if(req.method==="OPTIONS")return new Response("",{status:204,headers:C});if(req.method==="GET"){const me=await tg("getMe"),webhook=`${URL}/functions/v1/telegram-webhook`;await tg("deleteWebhook",{drop_pending_updates:true});await tg("setWebhook",{url:webhook,allowed_updates:["message","callback_query"],drop_pending_updates:false});const info=await tg("getWebhookInfo");return out({ok:true,configured:true,handler_version:24,bot:me.result?.username||me.result?.first_name,webhook_info:info.result})}if(req.method!=="POST")return out({ok:true,handler_version:24});const u=await req.json(),id=Number(u?.update_id);if(Number.isFinite(id)&&!(await dedupe(id)))return out({ok:true,duplicate:true,handler_version:24});const task=process(u);try{(globalThis as any).EdgeRuntime?.waitUntil?.(task)}catch{}return out({ok:true,accepted:true,handler_version:24})}catch(e){console.error(e);return out({ok:false,handler_version:24,error:e instanceof Error?e.message:"Unknown error"},500)}});