import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { INCOME_RULES, EXPENSE_RULES, normalize, canonicalCategoryName, inferTransactionType } from "https://raw.githubusercontent.com/jsuryanaads/WeMONEY/main/src/services/hybridAiRules.js";
import { classifyWithOpenRouter } from "./ai.ts";

const URL = Deno.env.get("SUPABASE_URL")!;
const KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(URL, KEY);
const C = { "Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods":"GET,POST,OPTIONS" };
const out = (x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json",...C}});
const rupiah=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const AI_THRESHOLD=0.70;

async function token(){const{data,error}=await db.rpc("get_telegram_bot_token");if(error||!data)throw Error("TELEGRAM_BOT_TOKEN belum dikonfigurasi");return String(data)}
async function tg(method:string,body:Record<string,unknown>={}){const r=await fetch(`https://api.telegram.org/bot${await token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!d.ok)throw Error(d.description||"Telegram API error");return d}
function typeOf(s:string){return inferTransactionType(s).type}
function amountOf(s:string){let r=s.toLowerCase().replace(/rp\.?/g,"").replace(/\s/g,"").trim(),m=r.match(/^(\d+(?:[.,]\d+)?)(juta|jt|ribu|rb|k|m)?$/i);if(!m)return null;let n=Number(m[1].replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(/,(?=\d{1,2}(?:$|[a-z]))/,"."));if(!Number.isFinite(n))return null;const u=(m[2]||"").toLowerCase();if(["juta","jt","m"].includes(u))n*=1e6;if(["ribu","rb","k"].includes(u))n*=1e3;return n>0?Math.round(n):null}
function parse(text:string){const type=typeOf(text),m=text.trim().match(/(?:rp\.?\s*)?\d[\d.,]*\s*(?:juta|jt|ribu|rb|k|m)?/i);if(!m)return null;const amount=amountOf(m[0]);if(!amount)return null;const description=text.replace(m[0],"").replace(/^(pemasukan|pengeluaran|masuk|keluar|income|expense|gaji|bonus|pendapatan|uang\s+masuk(?:\s+dari)?|uang\s+diterima(?:\s+dari)?|dapat\s+uang(?:\s+dari)?|terima\s+uang(?:\s+dari)?)\b\s*/i,"").replace(/^[\s:-]+|[\s]+$/g,"")||"Transaksi Telegram";return{type,amount,description:description.slice(0,180)}}
function categoryCandidates(text:string,type:string,cats:any[]){const pool=(cats||[]).filter(c=>c.is_active!==false&&c.type===type);const lower=normalize(text);return pool.map((c:any)=>{const name=canonicalCategoryName(c.name);let score=0,reason="";if(name&&lower.includes(name)){score=100;reason="nama kategori disebut"}const rules=type==="income"?INCOME_RULES:EXPENSE_RULES;for(const[r,patterns]of rules)if(canonicalCategoryName(r)===name&&patterns.some(x=>lower.includes(normalize(x)))){score=Math.max(score,90);reason=`kata kunci cocok dengan ${c.name}`}for(const t of name.split(/[^a-z0-9]+/).filter(x=>x.length>=3))if(lower.includes(t))score+=15;return{c,score,reason}}).sort((a,b)=>b.score-a.score)}

async function classify(uid:string,p:{type:"income"|"expense",amount:number,description:string}){
 const[{data:cats},{data:wallets}]=await Promise.all([db.from("categories").select("id,name,type,is_active").eq("user_id",uid).eq("is_active",true).eq("type",p.type),db.from("wallets").select("id,name,is_active").eq("user_id",uid).eq("is_active",true).order("created_at",{ascending:true})]);
 const ranked=categoryCandidates(p.description,p.type,cats||[]),best=ranked[0],strong=!!best&&best.score>=80,cat=strong?best.c:null,candidates=ranked.filter(x=>canonicalCategoryName(x.c.name)!=="lainnya").slice(0,3).map(x=>({id:x.c.id,name:x.c.name,score:x.score}));
 const wallet=(wallets||[]).find((w:any)=>normalize(p.description).includes(normalize(w.name)))||(wallets||[]).find((w:any)=>canonicalCategoryName(w.name)==="kas utama")||(wallets||[])[0];
 let result={categoryId:cat?.id||null,categoryName:cat?.name||null,categoryCandidates:candidates,walletId:wallet?.id||null,walletName:wallet?.name||null,confidence:strong&&wallet?.id?0.93:strong||wallet?.id?0.65:0.35,source:"local",model:null as string|null};
 if(result.confidence<AI_THRESHOLD){
   try{
    const ai=await classifyWithOpenRouter({text:p.description,amount:p.amount,transaction_date:new Date().toISOString().slice(0,10),categories:(cats||[]).map((c:any)=>({name:c.name,type:c.type})),wallets:(wallets||[]).map((w:any)=>({name:w.name}))});
    const r=ai?.result;
    const aiType=r?.type==="income"||r?.type==="expense"?r.type:null;
    const aiAmount=Number(r?.amount);
    const aiDate=typeof r?.transaction_date==="string"?r.transaction_date:null;
    const aiCat=(cats||[]).find((c:any)=>normalize(c.name)===normalize(String(r?.category_name||"")));
    const aiWallet=(wallets||[]).find((w:any)=>normalize(w.name)===normalize(String(r?.wallet_name||"")));
    const aiConfidence=Math.min(Math.max(Number(r?.confidence)||0,0),0.89);
    const valid=aiType===p.type&&aiAmount===p.amount&&!!aiDate&&/^(\d{4})-(\d{2})-(\d{2})$/.test(aiDate)&&!!aiCat&&!!aiWallet&&aiConfidence>=AI_THRESHOLD;
    if(valid){result={categoryId:aiCat.id,categoryName:aiCat.name,categoryCandidates:candidates,walletId:aiWallet.id,walletName:aiWallet.name,confidence:aiConfidence,source:"openrouter",model:ai?.model||null};}
   }catch(e){console.error("telegram openrouter fallback",e)}
 }
 return result;
}

function obligationAmountOf(s:string){const r=s.toLowerCase().replace(/rp\\.?/g,"").replace(/\\s/g,"").trim();const m=r.match(/^(\\d+(?:[.,]\\d+)?)(juta|jt|ribu|rb|k|m)?$/i);if(!m)return null;let n=Number(m[1].replace(/\\.(?=\\d{3}(?:\\D|$))/g,"").replace(",","."));if(!Number.isFinite(n))return null;const u=(m[2]||"").toLowerCase();if(["juta","jt","m"].includes(u))n*=1e6;if(["ribu","rb","k"].includes(u))n*=1e3;return n>0?Math.round(n):null}
function localDate(day:number){const d=new Date(),y=d.getFullYear(),m=d.getMonth()+1,max=new Date(y,m,0).getDate(),dd=Math.min(day,max);return y+"-"+String(m).padStart(2,"0")+"-"+String(dd).padStart(2,"0")}
function parseObligation(text:string){const s=text.trim(),m=s.match(/(?:rp\\.?\\s*)?\\d[\\d.,]*\\s*(?:juta|jt|ribu|rb|k|m)?/i),n=obligationAmountOf(m?.[0]||"");if(!n)return null;const kind=/(piutang|orang .* (hutang|utang)|dibayar ke saya|harus menerima)/i.test(s)?"receivable":/(hutang|utang|pinjam|meminjam)/i.test(s)?"debt":/(tagihan|listrik|internet|wifi|air|pln|cicilan|sewa|langganan)/i.test(s)?"bill":null;if(!kind)return null;const d=s.match(/(?:tanggal|tgl|jatuh tempo|tempo)\\s*(\\d{1,2})\\b/i)?.[1],due=d?localDate(Number(d)):"";const title=s.replace(/(?:rp\\.?\\s*)?\\d[\\d.,]*\\s*(?:juta|jt|ribu|rb|k|m)?/gi,"").replace(/(?:tanggal|tgl|jatuh tempo|tempo)\\s*\\d{1,2}/gi,"").replace(/\\s+/g," ").replace(/^(bayar|catat|tambahkan|tambah)\\s+/i,"").trim()||"Kewajiban baru";return{kind,amount_total:n,title:title.slice(0,180),due_date:due,is_recurring:/(setiap|tiap|bulanan|tahunan|per bulan|per tahun)/i.test(s),recurrence:/(tahunan|per tahun)/i.test(s)?"yearly":"monthly",notes:"",confidence:.82}}function command(msg:any){const raw=String(msg?.text??msg?.caption??"").replace(/[\u200B-\u200D\uFEFF]/g,"").trim();if(!raw.startsWith("/"))return{raw,cmd:"",arg:""};const first=raw.split(/\s+/)[0],m=first.match(/^\/([A-Za-z0-9_]+)(?:@([A-Za-z0-9_]+))?$/);return{raw,cmd:m?.[1]?.toLowerCase()||"",arg:raw.slice(first.length).trim()}}
async function dedupe(id:number){const{error}=await db.from("telegram_webhook_updates").insert({update_id:id});if(!error)return true;if(error.code==="23505")return false;console.error(error);return true}
function categoryKeyboard(candidates:any[]){return candidates.slice(0,3).map(c=>[{text:`📂 ${String(c.name).slice(0,30)}`,callback_data:`cat:${c.id}`}])}
async function sendConfirmation(chat:string,p:any){const rows=[];if(p.categoryCandidates?.length&&!p.category_id)rows.push(...categoryKeyboard(p.categoryCandidates));rows.push([{text:p.category_id?"✅ Simpan":"⚠️ Pilih Kategori",callback_data:p.category_id?"confirm":"noop"},{text:"❌ Batal",callback_data:"cancel"}]);await tg("sendMessage",{chat_id:chat,text:`🧾 *Konfirmasi Transaksi*\n\n${p.transaction_type==="expense"?"Pengeluaran":"Pemasukan"}: ${rupiah(Number(p.amount))}\nKeterangan: ${p.description}\nKategori: ${p.category_name||"⚠️ Belum yakin — pilih salah satu"}\nDompet: ${p.wallet_name||"⚠️ Belum ada"}\nAI confidence: ${Math.round(Number(p.ai_confidence||0)*100)}%${p.ai_source?`\nAI source: ${p.ai_source}${p.ai_model?` (${p.ai_model})`:""}`:""}\n\n${p.category_id?"Pilih tindakan:":"AI menemukan beberapa kandidat kategori. Pilih yang paling sesuai:"}`,parse_mode:"Markdown",reply_markup:{inline_keyboard:rows}})}

async function process(u:any){try{if(u.callback_query){const cb=u.callback_query,chat=String(cb.message?.chat?.id||""),data=String(cb.data||"");await tg("answerCallbackQuery",{callback_query_id:cb.id});const{data:cn}=await db.from("telegram_connections").select("user_id").eq("telegram_chat_id",chat).eq("status","active").maybeSingle();if(!cn)return;const{data:p}=await db.from("telegram_pending_transactions").select("*").eq("user_id",cn.user_id).eq("telegram_chat_id",chat).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!p){await tg("sendMessage",{chat_id:chat,text:"⚠️ Transaksi sudah kedaluwarsa. Silakan kirim ulang."});return}if(data==="cancel"){await db.from("telegram_pending_transactions").delete().eq("id",p.id);await tg("sendMessage",{chat_id:chat,text:"❌ Transaksi dibatalkan."});return}if(data==="noop"){await tg("sendMessage",{chat_id:chat,text:"⚠️ Pilih salah satu kategori terlebih dahulu."});return}if(data.startsWith("cat:")){const id=data.slice(4),{data:cat}=await db.from("categories").select("id,name,type,is_active").eq("id",id).eq("user_id",cn.user_id).eq("is_active",true).eq("type",p.transaction_type).maybeSingle();if(!cat){await tg("sendMessage",{chat_id:chat,text:"⚠️ Kategori tidak valid atau sudah tidak aktif."});return}await db.from("telegram_pending_transactions").update({category_id:cat.id,category_name:cat.name}).eq("id",p.id);await tg("sendMessage",{chat_id:chat,text:`📂 Kategori dipilih: *${cat.name}*`,parse_mode:"Markdown"});await sendConfirmation(chat,{...p,category_id:cat.id,category_name:cat.name});return}if(data==="confirm"){if(!p.category_id){await tg("sendMessage",{chat_id:chat,text:"⚠️ Pilih kategori terlebih dahulu sebelum menyimpan."});return}const{error}=await db.rpc("telegram_create_transaction",{p_chat_id:chat,p_type:p.transaction_type,p_amount:p.amount,p_description:p.description,p_date:p.transaction_date,p_wallet_id:p.wallet_id||null,p_category_id:p.category_id||null});if(error){await tg("sendMessage",{chat_id:chat,text:`❌ Gagal menyimpan transaksi: ${error.message}`});return}await db.from("telegram_pending_transactions").delete().eq("id",p.id);await tg("sendMessage",{chat_id:chat,text:`✅ *Tersimpan*\n${p.transaction_type==="expense"?"Pengeluaran":"Pemasukan"}: ${rupiah(Number(p.amount))}\nKeterangan: ${p.description}\nKategori: ${p.category_name}\nDompet: ${p.wallet_name||"Default"}\nTanggal: ${p.transaction_date}`,parse_mode:"Markdown"});return}return}
 const msg=u.message;if(!msg?.chat?.id)return;const chat=String(msg.chat.id),{raw,cmd,arg}=command(msg);if(cmd==="start"){await tg("sendMessage",{chat_id:chat,text:"🤖 *We MONEY Bot*\n\n/start — bantuan\n/hubungkan KODE — hubungkan akun\n/status — cek koneksi\n/batal — batalkan\n\nContoh:\n• `beli makan 25rb`\n• `uang masuk dari usaha 500rb`\n• `pemasukan gaji 5jt`\n\nBot meminta konfirmasi sebelum menyimpan.",parse_mode:"Markdown"});return}if(cmd==="hubungkan"){if(!arg){await tg("sendMessage",{chat_id:chat,text:"Gunakan: /hubungkan KODE\nKode dibuat di We MONEY → Pengaturan → Telegram."});return}const{error}=await db.rpc("telegram_link_account",{p_code:arg,p_chat_id:chat,p_username:msg.from?.username||null,p_first_name:msg.from?.first_name||null});await tg("sendMessage",{chat_id:chat,text:error?`❌ ${error.message}`:"✅ Telegram berhasil terhubung. Sekarang kirim transaksi seperti `beli makan 25rb`.",parse_mode:"Markdown"});return}if(cmd==="status"){const{data}=await db.from("telegram_connections").select("telegram_username").eq("telegram_chat_id",chat).eq("status","active").maybeSingle();await tg("sendMessage",{chat_id:chat,text:data?`🟢 Terhubung${data.telegram_username?` sebagai @${data.telegram_username}`:""}.`:"🔴 Belum terhubung."});return}if(cmd==="batal"){await db.from("telegram_pending_transactions").delete().eq("telegram_chat_id",chat);await tg("sendMessage",{chat_id:chat,text:"❌ Transaksi tertunda dibatalkan."});return}const{data:cn}=await db.from("telegram_connections").select("user_id").eq("telegram_chat_id",chat).eq("status","active").maybeSingle();if(!cn){await tg("sendMessage",{chat_id:chat,text:"🔒 Telegram belum terhubung. Buka We MONEY → Pengaturan → Telegram."});return}const obligation=parseObligation(raw);
if(obligation){
 await tg("sendMessage",{chat_id:chat,text:"🧾 *Interpretasi Hutang & Tagihan*\\n\\nJenis: "+(obligation.kind==="debt"?"Hutang":obligation.kind==="receivable"?"Piutang":"Tagihan")+"\\nNominal: "+rupiah(obligation.amount_total)+"\\nJudul: "+obligation.title+"\\nJatuh tempo: "+(obligation.due_date||"belum ditentukan")+"\\n\\n⚠️ Belum disimpan. Konfirmasi dan penyimpanan dilakukan di WeMONEY agar AI tidak dapat mengubah data keuangan secara langsung.",parse_mode:"Markdown"});
 return;
}
const p=parse(raw);if(!p){await tg("sendMessage",{chat_id:chat,text:"Format belum terbaca. Contoh: `beli makan 25rb` atau `uang masuk dari usaha 500rb`.",parse_mode:"Markdown"});return}const ai=await classify(cn.user_id,p);await db.from("telegram_pending_transactions").delete().eq("telegram_chat_id",chat);const{error}=await db.from("telegram_pending_transactions").insert({user_id:cn.user_id,telegram_chat_id:chat,transaction_type:p.type,amount:p.amount,description:p.description,wallet_id:ai.walletId,category_id:ai.categoryId,wallet_name:ai.walletName,category_name:ai.categoryName});if(error){await tg("sendMessage",{chat_id:chat,text:`❌ Gagal membuat draft: ${error.message}`});return}await sendConfirmation(chat,{transaction_type:p.type,amount:p.amount,description:p.description,wallet_id:ai.walletId,category_id:ai.categoryId,wallet_name:ai.walletName,category_name:ai.categoryName,categoryCandidates:ai.categoryCandidates,ai_confidence:ai.confidence,ai_source:ai.source,ai_model:ai.model});}catch(e){console.error("telegram process",e)}}
Deno.serve(async req=>{try{if(req.method==="OPTIONS")return new Response("",{status:204,headers:C});if(req.method==="GET"){const me=await tg("getMe"),webhook=`${URL}/functions/v1/telegram-webhook`;await tg("deleteWebhook",{drop_pending_updates:true});await tg("setWebhook",{url:webhook,allowed_updates:["message","callback_query"],drop_pending_updates:false});const info=await tg("getWebhookInfo");return out({ok:true,configured:true,handler_version:18,bot:me.result?.username||me.result?.first_name,webhook_info:info.result})}if(req.method!=="POST")return out({ok:true,handler_version:18});const u=await req.json(),id=Number(u?.update_id);if(Number.isFinite(id)&&!(await dedupe(id)))return out({ok:true,duplicate:true,handler_version:18});const task=process(u);try{(globalThis as any).EdgeRuntime?.waitUntil?.(task)}catch{}return out({ok:true,accepted:true,handler_version:18})}catch(e){console.error(e);return out({ok:false,handler_version:18,error:e instanceof Error?e.message:"Unknown error"},500)}});