import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const PROVIDERS=[{name:"pollinations-openai",url:"https://text.pollinations.ai/",model:"openai"},{name:"pollinations-mistral",url:"https://text.pollinations.ai/",model:"mistral"},{name:"pollinations-deepseek",url:"https://text.pollinations.ai/",model:"deepseek"}];
const cleanJson=(text:string)=>{const raw=String(text||"").trim().replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/```$/i,"").trim();const a=raw.indexOf("{");const b=raw.lastIndexOf("}");if(a<0||b<=a)throw Error("AI did not return JSON");return JSON.parse(raw.slice(a,b+1))};
const norm=(v:unknown)=>String(v||"").trim().toLowerCase();
function validate(r:any,cats:any[],wallets:any[]){const type=r?.type==="income"?"income":r?.type==="expense"?"expense":null;const amount=Number(r?.amount||0);if(!type||!Number.isFinite(amount)||amount<=0)return null;const cat=(cats||[]).find((x:any)=>x?.is_active!==false&&x?.type===type&&norm(x?.name)===norm(r?.category_name));const wallet=(wallets||[]).find((x:any)=>x?.is_active!==false&&norm(x?.name)===norm(r?.wallet_name));return{type,amount:Math.round(amount),transaction_date:/^\d{4}-\d{2}-\d{2}$/.test(String(r?.transaction_date||""))?r.transaction_date:"",description:String(r?.description||"").trim().slice(0,180),merchant:String(r?.merchant||"").trim().slice(0,120),categoryId:cat?.id||"",walletId:wallet?.id||"",classificationConfidence:Math.max(0,Math.min(.89,Number(r?.confidence||.65))),classificationSource:"free-cloud-fallback",classificationExplanation:String(r?.reason||"Saran AI cloud gratis; periksa sebelum menyimpan.").slice(0,300)}};
async function ask(p:any,prompt:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(p.url,{method:"POST",headers:{"content-type":"application/json"},signal:c.signal,body:JSON.stringify({model:p.model,jsonMode:true,json:true,messages:[{role:"system",content:"Classify Indonesian personal finance text. Return JSON only."},{role:"user",content:prompt}]})});if(!r.ok)throw Error(`HTTP ${r.status}`);const body=await r.text();if(!body)throw Error("Empty response");if((r.headers.get("content-type")||"").includes("application/json")){const d=JSON.parse(body);return d?.choices?.[0]?.message?.content||d?.text||JSON.stringify(d)}return body}finally{clearTimeout(t)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{if(req.method!=="POST")throw Error("Method not allowed");const b=await req.json(),text=String(b?.text||"").trim();if(!text)throw Error("Text is required");const cats=Array.isArray(b?.categories)?b.categories.slice(0,100):[],wallets=Array.isArray(b?.wallets)?b.wallets.slice(0,50):[];const prompt=`Analyze this transaction: ${text}\nExisting categories: ${JSON.stringify(cats.map((x:any)=>({name:x.name,type:x.type})))}\nExisting wallets: ${JSON.stringify(wallets.map((x:any)=>({name:x.name})))}\nReturn JSON only: type, amount, transaction_date, description, merchant, category_name, wallet_name, confidence, reason. Never invent category or wallet names.`;const errors=[];for(const p of PROVIDERS){try{const result=validate(cleanJson(await ask(p,prompt)),cats,wallets);if(result)return new Response(JSON.stringify({ok:true,provider:p.name,result}),{headers:{...cors,"Content-Type":"application/json"}});errors.push(`${p.name}: invalid-result`)}catch(e){errors.push(`${p.name}: ${e instanceof Error?e.message:"failed"}`)}}return new Response(JSON.stringify({ok:false,fallback:"local",errors}),{status:503,headers:{...cors,"Content-Type":"application/json"}})}catch(e){return new Response(JSON.stringify({ok:false,fallback:"local",error:e instanceof Error?e.message:"Fallback unavailable"}),{status:400,headers:{...cors,"Content-Type":"application/json"}})}});
