import { useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { BarChart3, Camera, CreditCard, LayoutDashboard, LogOut, Menu, Moon, Palette, Plus, Settings, Sun, Tags, Target, Wallet, X, Zap } from 'lucide-react'
import packageJson from '../../../package.json'
import { useAuth } from '../../hooks/useAuth'
import { useTheme } from '../../hooks/useTheme'
import { THEME_PRESETS } from '../../theme/themeTokens'
import { signOut } from '../../services/authService'
import QuickExpense from '../finance/QuickExpense'
import QuickPhotoExpense from '../finance/QuickPhotoExpense'
import WeMoneyLogo from '../brand/WeMoneyLogo'

const items = [['Dashboard', '/dashboard', LayoutDashboard], ['Transaksi', '/transaksi', CreditCard], ['Kategori', '/kategori', Tags], ['Dompet', '/dompet', Wallet], ['Anggaran', '/anggaran', Target], ['Laporan', '/laporan', BarChart3], ['Pengaturan', '/pengaturan', Settings]]

export default function AppShell({ title, children }) {
  const navigate = useNavigate(); const location = useLocation(); const { user } = useAuth(); const { theme, setTheme, visualTheme, setVisualTheme } = useTheme(); const [open, setOpen] = useState(false); const [themeOpen, setThemeOpen] = useState(false); const [captureOpen, setCaptureOpen] = useState(false); const [quickExpenseOpen, setQuickExpenseOpen] = useState(false); const [quickPhotoOpen, setQuickPhotoOpen] = useState(false); const [signingOut, setSigningOut] = useState(false)
  const name = user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'Pengguna'; const year = new Date().getFullYear(); const appVersion = `V${packageJson.version}`; const pageKey = location.pathname.replace(/^\//, '').replaceAll('/', '-') || 'dashboard'; const go = path => { setOpen(false); setCaptureOpen(false); setThemeOpen(false); navigate(path) }; const toggleTheme = () => setTheme(theme === 'dark' ? 'light' : 'dark')
  useEffect(() => { const openQuick = () => { setCaptureOpen(false); setQuickExpenseOpen(true) }; window.addEventListener('wemoney:open-quick', openQuick); return () => window.removeEventListener('wemoney:open-quick', openQuick) }, [])
  useEffect(() => { const handleKeyDown = event => { if (event.key !== 'Escape') return; setOpen(false); setCaptureOpen(false); setThemeOpen(false); if (quickExpenseOpen) setQuickExpenseOpen(false); if (quickPhotoOpen) setQuickPhotoOpen(false) }; window.addEventListener('keydown', handleKeyDown); return () => window.removeEventListener('keydown', handleKeyDown) }, [quickExpenseOpen, quickPhotoOpen])
  const openQuick = () => { setCaptureOpen(false); setQuickExpenseOpen(true) }
  const openPhoto = () => { setCaptureOpen(false); setQuickPhotoOpen(true) }
  const handleSignOut = async () => { if (signingOut) return; setSigningOut(true); const { error } = await signOut(); if (!error) { setOpen(false); navigate('/login', { replace: true }) } setSigningOut(false) }
  return <div className={`wm-shell wm-page-${pageKey} min-h-screen overflow-x-hidden transition-colors duration-200 lg:p-4 lg:pl-[304px]`}>
    <aside className={`${open ? 'translate-x-0' : '-translate-x-full'} wm-sidebar fixed inset-y-0 left-0 z-50 w-[min(18rem,85vw)] border p-4 shadow-xl transition-transform duration-200 sm:p-5 lg:inset-y-4 lg:left-4 lg:w-[272px] lg:translate-x-0 lg:rounded-2xl`}><div className="flex h-full flex-col">
      <div className="mb-6 flex items-start justify-between"><div className="min-w-0"><div className="mb-3 grid h-11 w-11 place-items-center rounded-xl p-0.5 shadow-md"><WeMoneyLogo size={44}/></div><div className="truncate text-2xl font-extrabold tracking-tight">We<span className="wm-brand-accent"> MONEY</span></div><p className="max-w-[14rem] text-[11px] leading-4 opacity-70">Catat Uangmu, Rencanakan Masa Depanmu</p></div><button className="ml-2 shrink-0 rounded-lg p-2 hover:bg-black/5 lg:hidden dark:hover:bg-white/5" onClick={()=>setOpen(false)} aria-label="Tutup menu"><X size={20}/></button></div>
      <nav className="space-y-1">{items.map(([label,path,Icon])=>{const active=location.pathname===path;return <button key={path} onClick={()=>go(path)} aria-current={active?'page':undefined} className={`wm-nav-item flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition-all duration-150 sm:px-4 ${active?'wm-nav-active':'opacity-75 hover:opacity-100'}`}><Icon size={19}/>{label}</button>})}</nav>
      <div className="mt-auto border-t pt-4 wm-divider"><button type="button" onClick={handleSignOut} disabled={signingOut} className="wm-logout flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition disabled:cursor-not-allowed disabled:opacity-60"><LogOut size={19}/>{signingOut ? 'Keluar...' : 'Keluar'}</button><div className="mt-3 text-xs leading-5 opacity-70">We MONEY {appVersion} | © {year} Created Jsuryana</div></div>
    </div></aside>
    {open&&<button aria-label="Tutup menu" className="fixed inset-0 z-40 bg-slate-950/30 backdrop-blur-[1px] lg:hidden" onClick={()=>setOpen(false)}/>}<div className="min-w-0"><header className="wm-header sticky top-4 z-30 flex min-h-16 items-center justify-between rounded-2xl border px-3 shadow-sm backdrop-blur-md sm:px-4 lg:px-6"><div className="flex min-w-0 items-center"><button className="rounded-lg p-2 hover:bg-black/5 lg:hidden dark:hover:bg-white/5" onClick={()=>setOpen(true)} aria-label="Buka menu"><Menu/></button><h1 className="ml-2 truncate font-bold lg:ml-0">{title}</h1></div><div className="ml-auto flex items-center gap-1.5 sm:gap-2">
      <div className="relative hidden sm:block"><button onClick={()=>setCaptureOpen(v=>!v)} aria-expanded={captureOpen} aria-haspopup="menu" aria-label="Buka menu pencatatan" title="Catat" className="wm-primary grid h-10 w-10 place-items-center rounded-xl shadow-md"><Plus size={19}/></button>{captureOpen&&<CaptureMenu onQuick={openQuick} onPhoto={openPhoto} desktop/>}</div>
      <div className="relative"><button onClick={()=>setThemeOpen(v=>!v)} aria-label="Pilih tema" title="Pilih tema" className="grid h-10 w-10 place-items-center rounded-xl opacity-70 hover:bg-black/5 hover:opacity-100 dark:hover:bg-white/5"><Palette size={19}/></button>{themeOpen&&<><button className="fixed inset-0 z-40 cursor-default" aria-label="Tutup pemilih tema" onClick={()=>setThemeOpen(false)}/><div className="absolute right-0 top-12 z-50 w-56 rounded-2xl border p-2 shadow-2xl wm-popover"><p className="px-3 py-2 text-[11px] font-extrabold uppercase tracking-wider opacity-60">Tema We MONEY</p>{Object.entries(THEME_PRESETS).map(([key,preset])=><button key={key} onClick={()=>{setVisualTheme(key);setThemeOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${visualTheme===key?'wm-theme-active':'opacity-80 hover:opacity-100'}`}><span className="h-3 w-3 rounded-full" style={{background:preset.vars.primary}}/><span className="min-w-0 flex-1"><span className="block">{preset.label}</span><span className="block text-[10px] font-normal opacity-60">{preset.description}</span></span></button>)}<div className="my-1 border-t wm-divider"/><button onClick={toggleTheme} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold opacity-80 hover:opacity-100">{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}Mode {theme==='dark'?'Terang':'Gelap'}</button></div></>}</div><button onClick={()=>navigate('/pengaturan')} className="flex min-w-0 items-center gap-2 rounded-xl p-1.5 hover:bg-black/5 dark:hover:bg-white/5" aria-label="Buka pengaturan akun"><span className="wm-avatar grid h-9 w-9 shrink-0 place-items-center rounded-full text-sm font-bold">{name.slice(0,2).toUpperCase()}</span><span className="hidden max-w-48 truncate text-sm font-semibold sm:block">{name}</span></button></div></header><main className="mx-auto w-full max-w-7xl p-3 pb-[calc(5rem+env(safe-area-inset-bottom))] sm:p-4 sm:pb-24 lg:mt-5 lg:p-8 lg:pb-8">{children}</main></div>
    <nav className="wm-mobile-nav fixed bottom-0 left-0 right-0 z-30 grid h-[calc(4rem+env(safe-area-inset-bottom))] grid-cols-5 pb-[env(safe-area-inset-bottom)] lg:hidden"><Mobile label="Home" path="/dashboard" Icon={LayoutDashboard} go={go} active={location.pathname==='/dashboard'}/><Mobile label="Transaksi" path="/transaksi" Icon={CreditCard} go={go} active={location.pathname==='/transaksi'}/><div className="relative -mt-5 mx-auto self-start"><button aria-label="Menu catat" aria-expanded={captureOpen} aria-haspopup="menu" title="Catat" onClick={()=>setCaptureOpen(v=>!v)} className="wm-fab grid h-14 w-14 place-items-center rounded-full shadow-xl"><Zap size={24} fill="currentColor"/></button>{captureOpen&&<CaptureMenu onQuick={openQuick} onPhoto={openPhoto}/>}</div><Mobile label="Laporan" path="/laporan" Icon={BarChart3} go={go} active={location.pathname==='/laporan'}/><Mobile label="Saya" path="/pengaturan" Icon={Settings} go={go} active={location.pathname==='/pengaturan'}/></nav>
    <QuickExpense open={quickExpenseOpen} onClose={()=>setQuickExpenseOpen(false)} />
    <QuickPhotoExpense open={quickPhotoOpen} onClose={()=>setQuickPhotoOpen(false)} />
  </div>
}
function CaptureMenu({ onQuick, onPhoto, desktop = false }) { return <div role="menu" className={`wm-capture-menu absolute z-50 rounded-2xl border bg-[var(--wm-surface)] text-[var(--wm-text)] p-1.5 shadow-2xl ${desktop ? 'right-0 top-12 w-48' : 'bottom-16 left-1/2 w-48 -translate-x-1/2'}`}><button role="menuitem" onClick={onQuick} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-extrabold hover:bg-black/5 dark:hover:bg-white/5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-white"><Zap size={17} fill="currentColor"/></span><span><b className="block">Catat Cepat</b><small className="font-medium opacity-60">Tulis nominal & keterangan</small></span></button><button role="menuitem" onClick={onPhoto} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-extrabold hover:bg-black/5 dark:hover:bg-white/5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sky-500 text-white"><Camera size={17}/></span><span><b className="block">Photo Catat</b><small className="font-medium opacity-60">Ambil / pilih foto struk</small></span></button></div> }
function Mobile({label,path,Icon,go,active}){return <button onClick={()=>go(path)} aria-current={active?'page':undefined} className={`grid min-w-0 place-items-center gap-0.5 px-1 text-[10px] font-semibold ${active?'wm-mobile-active':'opacity-60'}`}><Icon size={19}/><span className="max-w-full truncate">{label}</span></button>}
