import { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { BarChart3, CreditCard, LayoutDashboard, Menu, Moon, Plus, Settings, Sun, Tags, Wallet, WalletCards, X, Zap } from 'lucide-react'
import { useAuth } from '../../hooks/useAuth'
import { useTheme } from '../../hooks/useTheme'
import QuickExpense from '../finance/QuickExpense'

const items = [
  ['Dashboard', '/dashboard', LayoutDashboard],
  ['Transaksi', '/transaksi', CreditCard],
  ['Kategori', '/kategori', Tags],
  ['Dompet', '/dompet', Wallet],
  ['Laporan', '/laporan', BarChart3],
  ['Pengaturan', '/pengaturan', Settings],
]

export default function AppShell({ title, children }) {
  const navigate = useNavigate(); const location = useLocation(); const { user } = useAuth(); const { theme, setTheme } = useTheme(); const [open, setOpen] = useState(false); const [quickExpenseOpen, setQuickExpenseOpen] = useState(false)
  const name = user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'Pengguna'; const year = new Date().getFullYear(); const go = path => { setOpen(false); navigate(path) }; const toggleTheme = () => setTheme(theme === 'dark' ? 'light' : 'dark')
  return <div className="min-h-screen overflow-x-hidden bg-[#f1f5f9] text-slate-800 transition-colors duration-200 dark:bg-[#020617] lg:p-4 lg:pl-[304px]">
    <aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-50 w-[min(18rem,85vw)] border border-slate-200 bg-white p-4 shadow-xl transition-transform duration-200 sm:p-5 lg:inset-y-4 lg:left-4 lg:w-[272px] lg:translate-x-0 lg:rounded-2xl lg:shadow-lg dark:border-slate-700 dark:bg-slate-900`}><div className="flex h-full flex-col">
      <div className="mb-6 flex items-start justify-between"><div className="min-w-0"><div className="mb-3 grid h-11 w-11 place-items-center rounded-xl bg-blue-600 text-white shadow-md shadow-blue-600/20"><WalletCards size={23}/></div><div className="truncate text-2xl font-extrabold tracking-tight text-slate-900">We<span className="text-blue-600">Money</span></div><p className="max-w-[14rem] text-[11px] leading-4 text-slate-400">Catat Uangmu, Rencanakan Masa Depanmu</p></div><button className="ml-2 shrink-0 rounded-lg p-2 hover:bg-slate-100 lg:hidden dark:hover:bg-slate-800" onClick={()=>setOpen(false)} aria-label="Tutup menu"><X size={20}/></button></div>
      <nav className="space-y-1">{items.map(([label,path,Icon])=>{const active=location.pathname===path;return <button key={path} onClick={()=>go(path)} aria-current={active?'page':undefined} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition-all duration-150 sm:px-4 ${active?'bg-blue-600 text-white shadow-lg shadow-blue-600/20':'text-slate-500 hover:bg-slate-100 hover:text-slate-900 dark:hover:bg-slate-800 dark:hover:text-slate-100'}`}><Icon size={19}/>{label}</button>})}</nav>
      <button type="button" onClick={()=>setQuickExpenseOpen(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-extrabold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700"><Zap size={17} fill="currentColor"/>Quick Expense</button>
      <div className="mt-auto border-t border-slate-200 pt-4 text-xs leading-5 text-slate-400 dark:border-slate-700">WeMoney | V1.3.1<br/>© {year} Created Jsuryana</div>
    </div></aside>
    {open&&<button aria-label="Tutup menu" className="fixed inset-0 z-40 bg-slate-950/30 backdrop-blur-[1px] lg:hidden" onClick={()=>setOpen(false)}/>}<div className="min-w-0"><header className="sticky top-4 z-30 flex min-h-16 items-center justify-between rounded-2xl border border-slate-200 bg-white/95 px-3 shadow-sm backdrop-blur-md sm:px-4 lg:px-6 dark:border-slate-700 dark:bg-slate-900/95"><div className="flex min-w-0 items-center"><button className="rounded-lg p-2 hover:bg-slate-100 lg:hidden dark:hover:bg-slate-800" onClick={()=>setOpen(true)} aria-label="Buka menu"><Menu/></button><h1 className="ml-2 truncate font-bold text-slate-900 lg:ml-0 dark:text-slate-100">{title}</h1></div><div className="ml-auto flex items-center gap-1.5 sm:gap-2"><button onClick={()=>setQuickExpenseOpen(true)} aria-label="Quick Expense" title="Quick Expense" className="hidden h-10 items-center gap-2 rounded-xl bg-blue-600 px-3 text-sm font-extrabold text-white shadow-md shadow-blue-600/20 hover:bg-blue-700 sm:flex"><Zap size={17} fill="currentColor"/>Quick Expense</button><button onClick={toggleTheme} aria-label={theme==='dark'?'Gunakan tema terang':'Gunakan tema gelap'} title={theme==='dark'?'Tema terang':'Tema gelap'} className="grid h-10 w-10 place-items-center rounded-xl text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800">{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><button onClick={()=>navigate('/pengaturan')} className="flex min-w-0 items-center gap-2 rounded-xl p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Buka pengaturan akun"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-blue-100 text-sm font-bold text-blue-700 dark:bg-blue-900 dark:text-blue-200">{name.slice(0,2).toUpperCase()}</span><span className="hidden max-w-48 truncate text-sm font-semibold text-slate-700 sm:block dark:text-slate-200">{name}</span></button></div></header><main className="mx-auto w-full max-w-7xl p-3 pb-[calc(5rem+env(safe-area-inset-bottom))] sm:p-4 sm:pb-24 lg:mt-5 lg:p-8 lg:pb-8">{children}</main></div>
    <nav className="fixed bottom-0 left-0 right-0 z-30 grid h-[calc(4rem+env(safe-area-inset-bottom))] grid-cols-5 border-t border-slate-200 bg-white/95 pb-[env(safe-area-inset-bottom)] shadow-[0_-4px_18px_rgba(15,23,42,0.06)] backdrop-blur-md lg:hidden dark:border-slate-700 dark:bg-slate-900/95"><Mobile label="Dashboard" path="/dashboard" Icon={LayoutDashboard} go={go} active={location.pathname==='/dashboard'}/><Mobile label="Transaksi" path="/transaksi" Icon={CreditCard} go={go} active={location.pathname==='/transaksi'}/><button aria-label="Quick Expense" onClick={()=>setQuickExpenseOpen(true)} className="-mt-5 mx-auto grid h-14 w-14 place-items-center self-start rounded-full bg-blue-600 text-white shadow-xl shadow-blue-600/30"><Zap size={24} fill="currentColor"/></button><Mobile label="Laporan" path="/laporan" Icon={BarChart3} go={go} active={location.pathname==='/laporan'}/><Mobile label="Pengaturan" path="/pengaturan" Icon={Settings} go={go} active={location.pathname==='/pengaturan'}/></nav>
    <QuickExpense open={quickExpenseOpen} onClose={()=>setQuickExpenseOpen(false)} />
  </div>
}
function Mobile({label,path,Icon,go,active}){return <button onClick={()=>go(path)} aria-current={active?'page':undefined} className={`grid min-w-0 place-items-center gap-0.5 px-1 text-[10px] font-semibold ${active?'text-blue-600 dark:text-blue-400':'text-slate-500 dark:text-slate-400'}`}><Icon size={19}/><span className="max-w-full truncate">{label}</span></button>}
