import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, Lightbulb, Plus, TrendingDown, TrendingUp, Wallet } from 'lucide-react'
import AppShell from '../components/layout/AppShell'
import { useAuth } from '../hooks/useAuth'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { getTransactionsForPeriod } from '../services/transactionService'
import { getWalletBalances } from '../services/walletService'

const money = value => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0))
const localISO = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const monthNames = ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember']
function monthRange(year, month) { return [localISO(new Date(year, month, 1)), localISO(new Date(year, month + 1, 0))] }
function previousMonthRange(year, month) { const date = new Date(year, month - 1, 1); return monthRange(date.getFullYear(), date.getMonth()) }

export default function Dashboard() {
  const { user } = useAuth(); const navigate = useNavigate(); const now = new Date()
  const [period, setPeriod] = useState('month'); const [month, setMonth] = useState(now.getMonth()); const [rows, setRows] = useState([]); const [previousRows, setPreviousRows] = useState([]); const [wallets, setWallets] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [live, setLive] = useState(false)
  const range = useMemo(() => { const current = new Date(); if (period === 'week') { const start = new Date(current); start.setDate(current.getDate() - 6); return [localISO(start), localISO(current)] }; if (period === 'year') return [`${current.getFullYear()}-01-01`, `${current.getFullYear()}-12-31`]; return monthRange(current.getFullYear(), month) }, [period, month])
  const load = async () => { if (!user?.id) return; setLoading(true); setError(''); try { const [transactions, balances] = await Promise.all([getTransactionsForPeriod(user.id, range[0], range[1]), getWalletBalances(user.id)]); let previous = []; if (period === 'month') { const previousRange = previousMonthRange(now.getFullYear(), month); previous = await getTransactionsForPeriod(user.id, previousRange[0], previousRange[1]) }; setRows(transactions); setPreviousRows(previous); setWallets(balances) } catch (err) { setError(err.message || 'Gagal memuat dashboard.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [user?.id, range[0], range[1]])
  useEffect(() => { if (!user?.id) return; let timer; const refresh = () => { clearTimeout(timer); timer = setTimeout(() => window.dispatchEvent(new Event('wemoney:data-changed')), 150) }; const channel = supabase.channel(`wemoney-dashboard-${user.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'transactions', filter: `user_id=eq.${user.id}` }, refresh).on('postgres_changes', { event: '*', schema: 'public', table: 'transfers', filter: `user_id=eq.${user.id}` }, refresh).on('postgres_changes', { event: '*', schema: 'public', table: 'wallets', filter: `user_id=eq.${user.id}` }, refresh).subscribe(status => setLive(status === 'SUBSCRIBED')); return () => { clearTimeout(timer); supabase.removeChannel(channel) } }, [user?.id])
  useEffect(() => { const refresh = () => load(); window.addEventListener('wemoney:data-changed', refresh); return () => window.removeEventListener('wemoney:data-changed', refresh) }, [user?.id, range[0], range[1]])
  const totals = useMemo(() => rows.reduce((result, tx) => { if (tx.type === 'income' || tx.type === 'expense') result[tx.type] += Number(tx.amount || 0); return result }, { income: 0, expense: 0 }), [rows])
  const previousTotals = useMemo(() => previousRows.reduce((result, tx) => { if (tx.type === 'income' || tx.type === 'expense') result[tx.type] += Number(tx.amount || 0); return result }, { income: 0, expense: 0 }), [previousRows])
  const balance = wallets.reduce((sum, wallet) => sum + Number(wallet.balance || 0), 0); const net = totals.income - totals.expense
  const topCategories = useMemo(() => { const grouped = {}; rows.filter(tx => tx.type === 'expense').forEach(tx => { const key = tx.category?.name || 'Tanpa kategori'; grouped[key] = (grouped[key] || 0) + Number(tx.amount || 0) }); return Object.entries(grouped).sort((a, b) => b[1] - a[1]).slice(0, 4).map(([name, amount]) => ({ name, amount, percent: totals.expense ? Math.round(amount / totals.expense * 100) : 0 })) }, [rows, totals.expense])
  const comparison = useMemo(() => { if (period !== 'month') return null; const current = totals.expense; const previous = previousTotals.expense; if (!previous) return current ? 'Pengeluaran mulai terbentuk bulan ini.' : 'Belum ada pengeluaran bulan ini.'; const percent = Math.round(((current - previous) / previous) * 100); return percent > 0 ? `Pengeluaran naik ${percent}% dibanding bulan sebelumnya.` : percent < 0 ? `Pengeluaran turun ${Math.abs(percent)}% dibanding bulan sebelumnya.` : 'Pengeluaran sama seperti bulan sebelumnya.' }, [period, totals.expense, previousTotals.expense])
  const insight = useMemo(() => { if (!rows.length) return { icon: Lightbulb, title: 'Mulai dari Catat Cepat', text: 'Catat satu transaksi sekarang. We MONEY akan mulai membaca pola keuanganmu.' }; if (totals.expense > totals.income) return { icon: TrendingDown, title: 'Pengeluaran perlu perhatian', text: topCategories[0] ? `${topCategories[0].name} menyumbang ${topCategories[0].percent}% pengeluaran periode ini.` : 'Pengeluaran lebih besar daripada pemasukan pada periode aktif.' }; if (net > 0) return { icon: TrendingUp, title: 'Arus kas positif', text: `Kamu menyisakan ${money(net)} pada periode aktif. Pertahankan ruang ini untuk tujuan keuangan.` }; return { icon: Lightbulb, title: 'Jaga keseimbangan', text: 'Pemasukan dan pengeluaran relatif seimbang. Coba perhatikan kategori terbesar agar lebih terarah.' } }, [rows.length, totals, topCategories, net])
  const recent = rows.slice(0, 5); const InsightIcon = insight.icon
  return <AppShell title="Dashboard">
    <div className="wm-dashboard-head"><div><div className="wm-live-label"><span className={`wm-live-dot ${live ? 'is-live' : ''}`} />{live ? 'Data realtime aktif' : 'Menghubungkan realtime...'}</div><p className="mt-1 text-sm text-slate-500">{new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</p><h2 className="mt-1 text-xl font-extrabold sm:text-2xl">Selamat datang kembali 👋</h2><p className="text-sm text-slate-500">Pantau keuangan tanpa harus membuka banyak menu.</p></div><button type="button" onClick={() => window.dispatchEvent(new Event('wemoney:open-quick'))} className="wm-primary hidden min-h-11 items-center justify-center gap-2 rounded-xl px-5 text-sm font-extrabold sm:flex"><Plus size={18}/>Catat Cepat</button></div>
    <div className="wm-period-bar" role="group" aria-label="Periode dashboard">{[['month','Bulan Ini'],['week','Minggu Ini'],['year','Tahun Ini']].map(([key,label]) => <button key={key} type="button" onClick={() => setPeriod(key)} className={period === key ? 'is-active' : ''}>{label}</button>)}{period === 'month' && <select aria-label="Pilih bulan" value={month} onChange={e => setMonth(Number(e.target.value))}>{monthNames.map((name,index) => <option key={name} value={index}>{name}</option>)}</select>}</div>
    {error && <div role="alert" className="wm-error mb-4">{error}</div>}
    <section className="wm-balance-grid"><Metric title="Total Saldo" value={balance} icon={Wallet} tone="blue" loading={loading} subtitle={`${wallets.length} dompet aktif`}/><Metric title="Pemasukan" value={totals.income} icon={TrendingUp} tone="green" loading={loading} subtitle="Periode aktif"/><Metric title="Pengeluaran" value={totals.expense} icon={TrendingDown} tone="rose" loading={loading} subtitle="Periode aktif"/></section>
    <section className="wm-dashboard-grid"><div className="wm-panel"><div className="wm-panel-head"><div><h3>Ringkasan Keuangan</h3><p>Fokus pada angka yang paling penting.</p></div></div><div className="wm-flow-grid"><div><span>Pemasukan</span><b className="text-emerald-600">{money(totals.income)}</b></div><div><span>Pengeluaran</span><b className="text-rose-600">{money(totals.expense)}</b></div><div><span>Sisa periode</span><b className={net >= 0 ? 'text-emerald-600' : 'text-rose-600'}>{money(net)}</b></div></div>{comparison && <div className="wm-comparison"><TrendingDown size={16}/><span>{comparison}</span></div>}<div className="wm-insight"><span className="wm-insight-icon"><InsightIcon size={19}/></span><div><b>{insight.title}</b><p>{insight.text}</p></div></div></div><div className="wm-panel"><div className="wm-panel-head"><div><h3>Pengeluaran Terbesar</h3><p>Top kategori periode aktif.</p></div></div>{topCategories.length ? <div className="wm-category-list">{topCategories.map(item => <div key={item.name}><div className="flex items-center justify-between gap-3 text-sm"><b className="truncate">{item.name}</b><span>{money(item.amount)}</span></div><div className="wm-progress"><i style={{width:`${Math.min(100,item.percent)}%`}}/></div><small>{item.percent}% dari pengeluaran</small></div>)}</div> : <EmptyState text="Belum ada pengeluaran pada periode ini."/>}</div></section>
    <section className="wm-panel mt-4"><div className="wm-panel-head"><div><h3>Transaksi Terbaru</h3><p>Ringkas di dashboard, detail ada di Transaksi.</p></div><button type="button" onClick={() => navigate('/transaksi')} className="wm-link">Lihat semua <ArrowUpRight size={15}/></button></div>{recent.length ? <div className="wm-recent-list">{recent.map(tx => <div key={tx.id}><span className={`wm-tx-icon ${tx.type === 'income' ? 'income' : 'expense'}`}>{tx.type === 'income' ? '+' : '−'}</span><div className="min-w-0 flex-1"><b className="truncate">{tx.description || 'Tanpa keterangan'}</b><small>{tx.transaction_date} · {tx.category?.name || 'Tanpa kategori'}</small></div><strong className={tx.type === 'income' ? 'text-emerald-600' : 'text-rose-600'}>{tx.type === 'income' ? '+' : '-'}{money(tx.amount)}</strong></div>)}</div> : <EmptyState text="Belum ada transaksi. Gunakan Catat Cepat untuk memulai."/>}</section>
  </AppShell>
}
function Metric({ title,value,icon:Icon,tone,loading,subtitle }) { return <div className={`wm-metric wm-metric-${tone}`}><span className="wm-metric-icon"><Icon size={20}/></span><div className="min-w-0"><span>{title}</span>{loading ? <div className="wm-skeleton mt-2 h-7 w-32"/> : <strong>{money(value)}</strong>}<small>{subtitle}</small></div></div> }
function EmptyState({ text }) { return <div className="wm-empty"><span><Lightbulb size={18}/></span><p>{text}</p></div> }
