import { useState } from 'react'
import { BarChart3, Bell, ChevronDown, CreditCard, LayoutDashboard, Menu, Plus, Settings, Tags, TrendingDown, TrendingUp, Wallet, X } from 'lucide-react'
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts'

const chartData = [
  { name: '01', income: 450, expense: 180 }, { name: '05', income: 300, expense: 220 },
  { name: '10', income: 600, expense: 310 }, { name: '15', income: 420, expense: 260 },
  { name: '20', income: 720, expense: 350 }, { name: '25', income: 520, expense: 290 },
  { name: '30', income: 650, expense: 380 },
]
const transactions = [
  ['Gaji Bulanan', 'Pemasukan', '07 Sep 2026', 5000000, true],
  ['Belanja Groceries', 'Makanan', '06 Sep 2026', 350000, false],
  ['Pulsa & Internet', 'Tagihan', '05 Sep 2026', 150000, false],
  ['Transportasi', 'Transportasi', '04 Sep 2026', 125000, false],
]
function formatIDR(value) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value) }

export default function Dashboard() {
  const [open, setOpen] = useState(false)
  const [active, setActive] = useState('Dashboard')
  const nav = [['Dashboard', LayoutDashboard], ['Transaksi', CreditCard], ['Kategori', Tags], ['Laporan', BarChart3], ['Pengaturan', Settings]]
  return <div className="min-h-screen bg-slate-50 text-slate-800">
    <aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 w-64 border-r border-slate-200 bg-white p-5 transition-transform lg:translate-x-0`}>
      <div className="mb-8 flex items-center justify-between"><div><div className="text-2xl font-extrabold tracking-tight text-slate-900">We<span className="text-blue-600">Money</span></div><div className="text-xs text-slate-400">Catat Uangmu, Rencanakan Masa Depanmu</div></div><button onClick={()=>setOpen(false)} className="lg:hidden" aria-label="Tutup menu"><X size={20}/></button></div>
      <nav className="space-y-1">{nav.map(([label, Icon])=><button key={label} onClick={()=>{setActive(label);setOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold transition ${active===label?'bg-blue-600 text-white shadow-lg shadow-blue-600/20':'text-slate-500 hover:bg-slate-100 hover:text-slate-900'}`}><Icon size={19}/>{label}</button>)}</nav>
      <div className="absolute bottom-5 left-5 right-5 border-t border-slate-100 pt-4 text-xs text-slate-400">WeMoney V1<br/>© 2026 Created Jsuryana</div>
    </aside>
    <div className="lg:pl-64">
      <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur lg:px-8"><button onClick={()=>setOpen(true)} className="lg:hidden" aria-label="Buka menu"><Menu/></button><div className="hidden lg:block"><h1 className="font-bold text-slate-900">{active}</h1></div><div className="ml-auto flex items-center gap-4"><button className="rounded-xl p-2 hover:bg-slate-100" aria-label="Notifikasi"><Bell size={20}/></button><div className="flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">JS</div><div className="hidden sm:block"><div className="text-sm font-bold">Jsuryana</div><div className="text-xs text-slate-400">Pengguna</div></div><ChevronDown size={16}/></div></div></header>
      <main className="mx-auto max-w-7xl p-4 pb-24 lg:p-8 lg:pb-8">
        <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-slate-500">Senin, 7 September 2026</p><h2 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Selamat datang kembali 👋</h2><p className="mt-1 text-sm text-slate-500">Pantau kondisi keuanganmu hari ini.</p></div><button className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700"><Plus size={18}/> Tambah Transaksi</button></div>
        <div className="mb-6 flex gap-2 overflow-x-auto pb-1"><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Bulan Ini</button><button className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-500 ring-1 ring-slate-200">Minggu Ini</button><button className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-500 ring-1 ring-slate-200">Tahun Ini</button></div>
        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Summary title="Total Pemasukan" value={formatIDR(5250000)} icon={TrendingUp} tone="emerald"/><Summary title="Total Pengeluaran" value={formatIDR(3180000)} icon={TrendingDown} tone="rose"/><Summary title="Saldo" value={formatIDR(2070000)} icon={Wallet} tone="blue"/></section>
        <section className="mt-6 grid gap-6 lg:grid-cols-[1.6fr_1fr]"><div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Arus Keuangan</h3><p className="text-xs text-slate-400">Pemasukan vs pengeluaran</p></div><select className="rounded-lg border border-slate-200 px-3 py-2 text-xs" aria-label="Periode grafik"><option>September 2026</option></select></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="income" name="Pemasukan" fill="#2563eb" radius={[5,5,0,0]}/><Bar dataKey="expense" name="Pengeluaran" fill="#e11d48" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">Ringkasan</h3><div className="mt-5 space-y-5"><Progress label="Makanan" value="35%" width="35%"/><Progress label="Transportasi" value="20%" width="20%"/><Progress label="Belanja" value="15%" width="15%"/><Progress label="Tagihan" value="12%" width="12%"/><Progress label="Lainnya" value="18%" width="18%"/></div></div></section>
        <section className="mt-6 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-bold">Transaksi Terbaru</h3><p className="text-xs text-slate-400">Aktivitas keuangan terbaru</p></div><button className="text-sm font-bold text-blue-600">Lihat Semua</button></div><div className="divide-y divide-slate-100">{transactions.map(([name,cat,date,amount,income])=><div key={name} className="flex items-center justify-between gap-3 py-4"><div className="flex min-w-0 items-center gap-3"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${income?'bg-emerald-50 text-emerald-600':'bg-rose-50 text-rose-600'}`}>{income?<TrendingUp size={18}/>:<TrendingDown size={18}/>}</div><div className="min-w-0"><div className="truncate text-sm font-bold">{name}</div><div className="text-xs text-slate-400">{cat} · {date}</div></div></div><div className={`whitespace-nowrap text-sm font-extrabold ${income?'text-emerald-600':'text-rose-600'}`}>{income?'+':'-'}{formatIDR(amount)}</div></div>)}</div></section>
      </main>
      <nav className="fixed bottom-0 left-0 right-0 z-30 grid h-16 grid-cols-5 border-t border-slate-200 bg-white lg:hidden">{nav.slice(0,2).map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} className={`grid place-items-center text-[10px] font-semibold ${active===label?'text-blue-600':'text-slate-400'}`}><Icon size={20}/>{label}</button>)}<button className="-mt-5 mx-auto grid h-14 w-14 place-items-center rounded-full bg-blue-600 text-white shadow-xl" aria-label="Tambah transaksi"><Plus/></button>{nav.slice(3).map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} className={`grid place-items-center text-[10px] font-semibold ${active===label?'text-blue-600':'text-slate-400'}`}><Icon size={20}/>{label}</button>)}</nav>
    </div>
  </div>
}
function Summary({title,value,icon:Icon,tone}) { const styles={blue:'bg-blue-50 text-blue-600',emerald:'bg-emerald-50 text-emerald-600',rose:'bg-rose-50 text-rose-600'}; return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{title}</p><p className="mt-2 text-2xl font-extrabold tracking-tight text-slate-900">{value}</p></div><div className={`grid h-11 w-11 place-items-center rounded-xl ${styles[tone]}`}><Icon size={21}/></div></div></div> }
function Progress({label,value,width}) { return <div><div className="mb-2 flex justify-between text-xs font-semibold"><span>{label}</span><span className="text-slate-400">{value}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width}}/></div></div> }
