import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const KEY=Deno.env.get("OPENROUTER_API_KEY")||"";
const MODEL=Deno.env.get("OPENROUTER_MODEL")||"openrouter/free";
const clean=(text:string)=>{const raw=String(text||"").trim().replace(/^\\`\\`\\`json\\s*/i,"").replace(/^\\`\\`\\`\\s*/i,"").replace(/\\`\\`\\`$/i,"").trim();const a=raw.indexOf("{");const b=raw.lastIndexOf("}");if(a<0||b<=a)throw Error("Invalid AI JSON");return JSON.parse(raw.slice(a,b+1))};
const validDate=(v:any)=>/^\\d{4}-\\d{2}-\\d{2}$/.test(String(v||""));
function validate(r:any){
 const intent=["create_obligation","create_transaction","pay_obligation","unknown"].includes(r?.intent)?r.intent:"unknown";
 const kind=["debt","receivable","bill"].includes(r?.kind)?r.kind:null;
 const amount=Number(r?.amount_total??r?.amount??0);
 const confidence=Math.max(0,Math.min(.89,Number(r?.confidence)||0));
 if(intent==="create_obligation"&&!kind) return null;
 if(intent!=="create_obligation") return {intent,confidence,requires_confirmation:true};
 return {intent,kind,amount_total:Number.isFinite(amount)&&amount>0?Math.round(amount):0,title:String(r?.title||"").trim().slice(0,180),counterparty:String(r?.counterparty||"").trim().slice(0,120),due_date:validDate(r?.due_date)?r.due_date:"",is_recurring:Boolean(r?.is_recurring),recurrence:r?.recurrence==="yearly"?"yearly":"monthly",notes:String(r?.notes||"").trim().slice(0,500),confidence,requires_confirmation:true};
}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{if(req.method!=="POST")throw Error("Method not allowed");const body=await req.json();const text=String(body?.text||"").trim();if(!text)throw Error("Text is required");if(!KEY)return new Response(JSON.stringify({ok:false,provider:"local",error:"OpenRouter is not configured"}),{status:503,headers:{...cors,"Content-Type":"application/json"}});const prompt="Interpret this Indonesian personal-finance message. Return JSON only.\nMessage: "+text+"\nToday: "+new Date().toISOString().slice(0,10)+"\nIntent must be one of create_obligation, create_transaction, pay_obligation, unknown. For create_obligation, kind must be debt, receivable, or bill. Do not invent amounts, dates, counterparties, categories, wallets, or IDs. If a day-only date is stated, resolve it in the current month. Return: intent, kind, amount_total, title, counterparty, due_date, is_recurring, recurrence, notes, confidence.";const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),9000);try{const response=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+KEY,"HTTP-Referer":"https://jsuryanaads.github.io/WeMONEY/","X-Title":"WeMONEY Hybrid AI"},signal:controller.signal,body:JSON.stringify({model:MODEL,temperature:0,response_format:{type:"json_object"},messages:[{role:"system",content:"You are a conservative finance intent parser. Never mutate data and never invent missing facts."},{role:"user",content:prompt}]})});if(!response.ok)throw Error("OpenRouter HTTP "+response.status);const data=await response.json();const result=validate(clean(data?.choices?.[0]?.message?.content));if(!result)throw Error("Invalid intent result");return new Response(JSON.stringify({ok:true,provider:"openrouter",model:MODEL,result}),{headers:{...cors,"Content-Type":"application/json"}})}finally{clearTimeout(timer)}}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:"AI intent unavailable"}),{status:400,headers:{...cors,"Content-Type":"application/json"}})}});